### ISSUE TITLE
你好 

### ISSUE THREAD

**Issue by wwwsoftwares** [k-dylan/easyclub#2]
easyclub 写的不错，这个有后台系统么。怎么做文档管理呢

**Comment by k-dylan** [comment]
我最近事情比较多,好久没有更新了. 目前easyclub还没有添加后台,在前台登录管理员帐号之后,可以做帖子的修改删除等操作.

**Comment by wwwsoftwares** [comment]
哈哈  我们已经在改造这个东西 感觉还不错

在 2017-03-19 15:06:09，"kdylan" <notifications@github.com> 写道：


我最近事情比较多,好久没有更新了. 目前easyclub还没有添加后台,在前台登录管理员帐号之后,可以做帖子的修改删除等操作.
