### ISSUE TITLE
session store is unavailable

### ISSUE THREAD

**Issue by YuxinChou** [k-dylan/easyclub#7]
请问这个问题是代码错误？
```
(node:56798) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: session store is unavailable
(node:56798) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by k-dylan** [comment]
https://github.com/k-dylan/easyclub/blob/7aca29f49c29bec4b88b6256a4e49b4a61b0ab23/app.js#L29
你修改这里了么

**Comment by k-dylan** [comment]
redis 服务配置好了么

**Comment by YuxinChou** [comment]
配置好了，截图如下：

![cc34ee51-aa6c-4646-a510-ce8a2c87eab9](https://user-images.githubusercontent.com/7675333/32770263-f7312d2a-c959-11e7-91c7-f7eb8a768da6.png)

我是在服务器跑了一个mongodb，redis，本地启动项目。

**Comment by YuxinChou** [comment]
@k-dylan 这个是什么意思？我没有改，改成什么？

```
let assets = {};
app.keys = ['easyclub'];
```

**Comment by YuxinChou** [comment]
@k-dylan 
哈喽，dylan。
我刚刚把代码丢到服务器上，在服务器上运行项目，即：项目和数据库、redis在同一个位置，发现没有遇到这个报错。
但是项目在本地，连接服务器就会遇到报错，你可以试试。看下有没有解决方法，谢谢。

**Comment by YuxinChou** [comment]
@k-dylan 哈喽，dylan。
问题解决了，是本地跑项目的时候，无法连接远程redis所致，要修改redis配置开放。
```
let assets = {};
app.keys = ['easyclub'];
```
这个貌似没有用吧。

**Comment by k-dylan** [comment]
@YuxinChou 我记得这个keys是在session那个插件用的 好久没看这个项目了  记不太清楚了
